// this file segments the visitor code to ensure modularity - visitors.js handles all the gameplay / interaction logic, whereas this file is the actual drawing of them on the map using their pngs

import { getnpcs_on_map } from "../logic/visitorLogic/visitors.js";  // I just use this to details about the visitors already in play

// these are the list of all the pngs created to represent the visitors to durham lumiere
const VISITOR_SPRITES = [
  "./assets/imgs/sprites/Boy Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Happy Dad Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Mum Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Stressed Dad Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Teenage Daughter Sprite - Generated by ChatGPT.png",
];


// I define this as a singular function to load the sprite onto the map and draw on their png to represnt them
export function draw_visitor_sprites_onto_map() {
    const lumiere_map = document.getElementById("grid");  // fetch the map from the DOM

    // I just remove all previous npcs and redraw them later
    const all_available_npcs = document.querySelectorAll(".npc-sprite");  // i.e. everything on the map w/ npc class

    // then go through list of npcs & remove them 1 by 1
    for (let i = 0; i < all_available_npcs.length; i++) {
        const specific_npc = all_available_npcs[i];
        specific_npc.remove();
    }

    // i didn't remove their logic representations though; this is where I fetch them and iterate through
    let visitors_in_the_game = getnpcs_on_map();

    for (const npc of visitors_in_the_game) {
        // is the npc doesn't alredy have a random sprite, they're getting one now!
        if (!npc.sprite) {
            const ran_sprite_num = Math.floor(Math.random() * VISITOR_SPRITES.length);  // random snew_sprite_repection for now, though I'll probably change later
            npc.sprite = VISITOR_SPRITES[ran_sprite_num];
        }

        // now the new sprite needs an img obj created for it on the map
        const new_sprite_rep = document.createElement("img");
        new_sprite_rep.src = npc.sprite;  // w/ random img from above
        new_sprite_rep.classList.add("npc-sprite");  // now adding to the list of overall npcs

        new_sprite_rep.style.position = "absolute";
        new_sprite_rep.style.left = `calc(${npc.vis_x_pos} * var(--cell-size))`;
        new_sprite_rep.style.top  = `calc(${npc.vis_y_pos} * var(--cell-size))`;
        new_sprite_rep.style.width = `var(--cell-size)`;
        new_sprite_rep.style.height = `var(--cell-size)`;

        // I have to make sure that npcs don't block mouse clicks
        new_sprite_rep.style.pointerEvents = "none";
        new_sprite_rep.style.zIndex = "10";  // I need them to be below the placment preview to not interefere w/ it

        lumiere_map.appendChild(new_sprite_rep);
    }
}
