// this file segments the visitor code to ensure modularity - visitors.js handles all the gameplay / interaction logic, whereas this file is the actual drawing of them on the map using their pngs

import { getnpcs_on_map, STATE_OF_NPC } from "../logic/visitorLogic/visitors.js";  // I just use this to details about the visitors already in play

const HUNGER_BUBBLE_IMG = "./assets/imgs/Speech%20Bubble%20-%20Generated%20by%20ChatGPT.png"; // lives in root imgs folder

// these are the list of all the pngs created to represent the visitors to durham lumiere
const VISITOR_SPRITES = [
  "./assets/imgs/sprites/Boy Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Happy Dad Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Mum Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Stressed Dad Sprite - Generated by ChatGPT.png",
  "./assets/imgs/sprites/Teenage Daughter Sprite - Generated by ChatGPT.png",
];


// I define this as a singular function to load the sprite onto the map and draw on their png to represnt them
export function draw_visitor_sprites_onto_map() {
    const lumiere_map = document.getElementById("grid");  // fetch the map from the DOM

    // I just remove all previous npcs and redraw them later
    const all_available_npcs = document.querySelectorAll(".npc-sprite");  // i.e. everything on the map w/ npc class
    // & same w/ progress bars above the hears of all durham's visitors
    const all_progress_bars = document.querySelectorAll(".npc-progress");
    all_progress_bars.forEach(progbar => progbar.remove());
    // and also wipe any hunger bubbles so they don't duplicate
    const all_hunger_bubbles = document.querySelectorAll(".npc-hungry-bubble");
    all_hunger_bubbles.forEach(bubble => bubble.remove());

    // then go through list of npcs & remove them 1 by 1
    for (let i = 0; i < all_available_npcs.length; i++) {
        const specific_npc = all_available_npcs[i];
        specific_npc.remove();
    }

    // i didn't remove their logic representations though; this is where I fetch them and iterate through
    let visitors_in_the_game = getnpcs_on_map();

    for (const npc of visitors_in_the_game) {
        // is the npc doesn't alredy have a random sprite, they're getting one now!
        if (!npc.sprite) {
            const ran_sprite_num = Math.floor(Math.random() * VISITOR_SPRITES.length);  // random snew_sprite_repection for now, though I'll probably change later
            npc.sprite = VISITOR_SPRITES[ran_sprite_num];
        }

        // now the new sprite needs an img obj created for it on the map
        const new_sprite_rep = document.createElement("img");
        new_sprite_rep.src = npc.sprite;  // w/ random img from above
        new_sprite_rep.classList.add("npc-sprite");  // now adding to the list of overall npcs

        new_sprite_rep.style.position = "absolute"; // i put core css here so it can be easily modified without having to jump into the css file
        new_sprite_rep.style.left = `calc(${npc.vis_col} * var(--cell-size))`;
        new_sprite_rep.style.top  = `calc(${npc.vis_row} * var(--cell-size))`;
        new_sprite_rep.style.width = `var(--cell-size)`;
        new_sprite_rep.style.height = `var(--cell-size)`;

        // I have to make sure that npcs don't block mouse clicks
        new_sprite_rep.style.pointerEvents = "none";
        new_sprite_rep.style.zIndex = "10";  // I need them to be below the placment preview to not interefere w/ it

        lumiere_map.appendChild(new_sprite_rep);

        // the next part is to add the progress bars above the heads of durham visitors to show how long the npcs take interacting w/ each attraction
        if ( // i.e. if the visitor is there and still interacting
          npc.STATE_OF_NPC === STATE_OF_NPC.VISITING &&
          npc.interactionTotal > 0 && npc.interactionTimer >= 0 
        ) {
            const visitors_curr_prog = 1 - (npc.interactionTimer / npc.interactionTotal);
            const fit_to_visitor = Math.max(0, Math.min(1,  visitors_curr_prog));

            const progressContainer = document.createElement("div");  // this needs to be added to html to appear above heads
            progressContainer.classList.add("npc-progress");
            progressContainer.style.position = "absolute";
            progressContainer.style.left = `calc(${npc.vis_col} * var(--cell-size))`;

            // now I add a bit of inline css here to position the bar right above the visitor's head
            progressContainer.style.top  = `calc(${npc.vis_row} * var(--cell-size) - 4px)`;
            progressContainer.style.width = `var(--cell-size)`;
            progressContainer.style.height = "4px";
            progressContainer.style.pointerEvents = "none";
            progressContainer.style.zIndex = "11";

            const progressFill = document.createElement("div");
            progressFill.classList.add("npc-progress-fill");
            progressFill.style.width = `${fit_to_visitor * 100}%`;

            progressContainer.appendChild(progressFill);
            lumiere_map.appendChild(progressContainer);

            // show a little food bubble if this visitor is draining magic due to no nearby food
            if (npc.isHungryForFood) {
                const hungerBubble = document.createElement("img");
                hungerBubble.src = HUNGER_BUBBLE_IMG;
                hungerBubble.classList.add("npc-hungry-bubble");
                hungerBubble.style.position = "absolute";
                hungerBubble.style.left = `calc(${npc.vis_col} * var(--cell-size) + 4px)`;
                hungerBubble.style.top  = `calc(${npc.vis_row} * var(--cell-size) - 18px)`;
                hungerBubble.style.width = "18px";
                hungerBubble.style.height = "18px";
                hungerBubble.style.pointerEvents = "none";
                hungerBubble.style.zIndex = "12";
                lumiere_map.appendChild(hungerBubble);
            }
        }
    }
}
